services:
  esphome:
    image: ghcr.io/esphome/esphome:latest
    container_name: esphome
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host


